/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/ingest-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ingest Progress */
        get: operations["ingest_progress_api_v1_admin_ingest_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingest-snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ingest Snapshot */
        get: operations["ingest_snapshot_api_v1_admin_ingest_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get States */
        get: operations["get_states_api_v1_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/states/{state_code}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timeline */
        get: operations["get_timeline_api_v1_states__state_code__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/states/{state_code}/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Districts */
        get: operations["get_districts_api_v1_states__state_code__districts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Members */
        get: operations["get_members_api_v1_members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{bioguide_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Member */
        get: operations["get_member_api_v1_members__bioguide_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bills/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent Bills */
        get: operations["recent_bills_api_v1_bills_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bills/{bill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bill Detail */
        get: operations["bill_detail_api_v1_bills__bill_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityItem */
        ActivityItem: {
            /** Bill Id */
            bill_id: string;
            /** Title */
            title: string;
            /** Activity Type */
            activity_type: string;
            /** Congress */
            congress: number;
        };
        /** AdminIngestSnapshot */
        AdminIngestSnapshot: {
            /** Congress */
            congress: number;
            govinfo: components["schemas"]["GovInfoCoverage"];
            govinfo_jobs: components["schemas"]["JobStatusCounts"];
            govinfo_batch_jobs: components["schemas"]["JobStatusCounts"];
            index_jobs: components["schemas"]["JobStatusCounts"];
            reconcile_jobs: components["schemas"]["JobStatusCounts"];
            staging: components["schemas"]["StagingStatus"];
            /** Ready For Reconciliation */
            ready_for_reconciliation: boolean;
            /** Ready For Cutover */
            ready_for_cutover: boolean;
        };
        /** BillDetail */
        BillDetail: {
            /** Bill Id */
            bill_id: string;
            /** Title */
            title: string;
            /** Congress */
            congress?: number | null;
            /** Bill Type */
            bill_type?: string | null;
            /** Number */
            number?: string | null;
            /** Origin Chamber */
            origin_chamber?: string | null;
            /** Origin Chamber Code */
            origin_chamber_code?: string | null;
            /** Introduced Date */
            introduced_date?: string | null;
            /** Update Date */
            update_date?: string | null;
            /** Update Date Including Text */
            update_date_including_text?: string | null;
            /** Latest Action */
            latest_action?: {
                [key: string]: unknown;
            } | null;
            /** Policy Area */
            policy_area?: string | null;
            /** Sponsors */
            sponsors?: {
                [key: string]: unknown;
            }[];
            /** Subjects */
            subjects?: {
                [key: string]: unknown;
            } | null;
            /** Laws */
            laws?: {
                [key: string]: unknown;
            }[];
            /** Constitutional Authority Statement Text */
            constitutional_authority_statement_text?: string | null;
            /** Full Text */
            full_text?: string | null;
            /** Relationship Counts */
            relationship_counts?: {
                [key: string]: number;
            };
        };
        /** BillDetailResponse */
        BillDetailResponse: {
            bill: components["schemas"]["BillDetail"];
        };
        /** BillSummary */
        BillSummary: {
            /** Bill Id */
            bill_id: string;
            /** Title */
            title: string;
            /** Congress */
            congress?: number | null;
            /** Bill Type */
            bill_type?: string | null;
            /** Number */
            number?: string | null;
            /** Chamber */
            chamber?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** BillsResponse */
        BillsResponse: {
            /** Bills */
            bills: components["schemas"]["BillSummary"][];
            /** Total */
            total: number;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Limit
             * @default 50
             */
            limit: number;
        };
        /** ChamberTimeline */
        ChamberTimeline: {
            /** Chamber */
            chamber: string;
            /** Members */
            members: components["schemas"]["TimelineMember"][];
            /** Groups */
            groups?: components["schemas"]["CongressGroup"][];
        };
        /** CongressGroup */
        CongressGroup: {
            /** Congress */
            congress: number;
            /** Members */
            members: components["schemas"]["TimelineMember"][];
        };
        /** GovInfoCoverage */
        GovInfoCoverage: {
            /** Congress */
            congress: number;
            /**
             * Expected
             * @default 0
             */
            expected: number;
            /**
             * Available
             * @default 0
             */
            available: number;
            /**
             * Pending
             * @default 0
             */
            pending: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Not Available
             * @default 0
             */
            not_available: number;
            /**
             * Complete
             * @default false
             */
            complete: boolean;
            /**
             * Report Found
             * @default false
             */
            report_found: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestProgressJob */
        IngestProgressJob: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Resource */
            resource: string;
            /** From Date */
            from_date?: string | null;
            /** To Date */
            to_date?: string | null;
            /** Fetch Items */
            fetch_items: boolean;
            /** Hydrated */
            hydrated: number;
            /** Discovered */
            discovered: number;
            /** Target */
            target: number;
            /** Remaining */
            remaining: number;
        };
        /** IngestProgressResponse */
        IngestProgressResponse: {
            /** Hydrated */
            hydrated: number;
            /** Discovered */
            discovered: number;
            /** Target */
            target: number;
            /** Remaining */
            remaining: number;
            /** Active Jobs */
            active_jobs: number;
            /** Jobs */
            jobs: components["schemas"]["IngestProgressJob"][];
        };
        /** JobStatusCounts */
        JobStatusCounts: {
            /**
             * Queued
             * @default 0
             */
            queued: number;
            /**
             * Running
             * @default 0
             */
            running: number;
            /**
             * Retrying
             * @default 0
             */
            retrying: number;
            /**
             * Succeeded
             * @default 0
             */
            succeeded: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
        };
        /** MemberProfileResponse */
        MemberProfileResponse: {
            member: components["schemas"]["MemberSummary"];
            /** Recent Activity */
            recent_activity: components["schemas"]["ActivityItem"][];
            /** Topics */
            topics: components["schemas"]["TopicItem"][];
        };
        /** MemberSummary */
        MemberSummary: {
            /** Bioguide Id */
            bioguide_id: string;
            /** Display Name */
            display_name: string;
            /** Party */
            party: string;
            /** State */
            state: string;
            /** Chamber */
            chamber?: string | null;
            /** District */
            district?: number | null;
            /** Term Start Year */
            term_start_year?: number | null;
            /** Term End Year */
            term_end_year?: number | null;
            /** Image Url */
            image_url?: string | null;
        };
        /** MembersResponse */
        MembersResponse: {
            /** Members */
            members: components["schemas"]["MemberSummary"][];
            /** Total */
            total: number;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Limit
             * @default 50
             */
            limit: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Types */
            types: string[];
            /** Limit */
            limit: number;
            /** Results */
            results: components["schemas"]["SearchResultItem"][];
        };
        /** SearchResultItem */
        SearchResultItem: {
            /** Id */
            id: string;
            /** Result Type */
            result_type: string;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle?: string | null;
        };
        /** StagingStatus */
        StagingStatus: {
            /** Index */
            index: string;
            /**
             * Exists
             * @default false
             */
            exists: boolean;
            /**
             * Documents
             * @default 0
             */
            documents: number;
            /** Production Alias Target */
            production_alias_target?: string | null;
            /**
             * Connected
             * @default false
             */
            connected: boolean;
        };
        /** StateSummary */
        StateSummary: {
            /**
             * Code
             * @description Two-letter state code
             */
            code: string;
            /**
             * Name
             * @description State display name
             */
            name: string;
        };
        /** StateTimelineResponse */
        StateTimelineResponse: {
            /** State Code */
            state_code: string;
            /** State Name */
            state_name: string;
            house: components["schemas"]["ChamberTimeline"];
            senate: components["schemas"]["ChamberTimeline"];
        };
        /** TimelineMember */
        TimelineMember: {
            /** Bioguide Id */
            bioguide_id: string;
            /** Name */
            name: string;
            /** Party */
            party: string;
            /** Congress Start */
            congress_start: number;
            /** Congress End */
            congress_end: number;
        };
        /** TopicItem */
        TopicItem: {
            /** Label */
            label: string;
            /** Weight */
            weight: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ingest_progress_api_v1_admin_ingest_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestProgressResponse"];
                };
            };
        };
    };
    ingest_snapshot_api_v1_admin_ingest_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminIngestSnapshot"];
                };
            };
        };
    };
    get_states_api_v1_states_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateSummary"][];
                };
            };
        };
    };
    get_timeline_api_v1_states__state_code__timeline_get: {
        parameters: {
            query?: {
                from_congress?: number | null;
                to_congress?: number | null;
            };
            header?: never;
            path: {
                state_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateTimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_districts_api_v1_states__state_code__districts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                state_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_members_api_v1_members_get: {
        parameters: {
            query?: {
                query?: string | null;
                state?: string | null;
                chamber?: string | null;
                party?: string | null;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_member_api_v1_members__bioguide_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bioguide_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
                types?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_bills_api_v1_bills_recent_get: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
                query?: string | null;
                congress?: number | null;
                bill_type?: string | null;
                chamber?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bill_detail_api_v1_bills__bill_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
