/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/topic-training": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topic Training Status */
        get: operations["topic_training_status_api_v1_admin_topic_training_get"];
        put?: never;
        /** Topic Training Start */
        post: operations["topic_training_start_api_v1_admin_topic_training_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/member-graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Member Graph Status */
        get: operations["member_graph_status_api_v1_admin_member_graph_get"];
        put?: never;
        /** Member Graph Build */
        post: operations["member_graph_build_api_v1_admin_member_graph_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingest-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ingest Progress */
        get: operations["ingest_progress_api_v1_admin_ingest_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingest-snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ingest Snapshot */
        get: operations["ingest_snapshot_api_v1_admin_ingest_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/system-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["system_status_api_v1_admin_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get States */
        get: operations["get_states_api_v1_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/states/{state_code}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timeline */
        get: operations["get_timeline_api_v1_states__state_code__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/states/{state_code}/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Districts */
        get: operations["get_districts_api_v1_states__state_code__districts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Members */
        get: operations["get_members_api_v1_members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{bioguide_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Member */
        get: operations["get_member_api_v1_members__bioguide_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{bioguide_id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Member Activity */
        get: operations["get_member_activity_api_v1_members__bioguide_id__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{bioguide_id}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Member Topics */
        get: operations["member_topics_api_v1_members__bioguide_id__topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{bioguide_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Similar Members */
        get: operations["similar_members_api_v1_members__bioguide_id__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bills/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent Bills */
        get: operations["recent_bills_api_v1_bills_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bills/{bill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bill Detail */
        get: operations["bill_detail_api_v1_bills__bill_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bills/{bill_id}/votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bill Votes */
        get: operations["bill_votes_api_v1_bills__bill_id__votes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bills/{bill_id}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bill Topics */
        get: operations["bill_topics_api_v1_bills__bill_id__topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topics List */
        get: operations["topics_list_api_v1_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topic Trends */
        get: operations["topic_trends_api_v1_topics_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topic Detail */
        get: operations["topic_detail_api_v1_topics__topic_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subjects List */
        get: operations["subjects_list_api_v1_subjects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects/policy-area-trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policy Area Trends */
        get: operations["policy_area_trends_api_v1_subjects_policy_area_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/neighborhood": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Neighborhood */
        get: operations["neighborhood_api_v1_graph_neighborhood_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityItem */
        ActivityItem: {
            /** Bill Id */
            bill_id: string;
            /** Title */
            title: string;
            /** Activity Type */
            activity_type: string;
            /** Congress */
            congress: number;
        };
        /** AdminIngestSnapshot */
        AdminIngestSnapshot: {
            /** Congress */
            congress: number;
            govinfo: components["schemas"]["GovInfoCoverage"];
            govinfo_jobs: components["schemas"]["JobStatusCounts"];
            govinfo_batch_jobs: components["schemas"]["JobStatusCounts"];
            index_jobs: components["schemas"]["JobStatusCounts"];
            reconcile_jobs: components["schemas"]["JobStatusCounts"];
            staging: components["schemas"]["StagingStatus"];
            /** Ready For Reconciliation */
            ready_for_reconciliation: boolean;
            /** Ready For Cutover */
            ready_for_cutover: boolean;
        };
        /** BackfillProgress */
        BackfillProgress: {
            /** Total */
            total: number;
            /** Succeeded */
            succeeded: number;
            /** Pending */
            pending: number;
            /** Failed */
            failed: number;
            /**
             * Percent
             * @description Completion percentage, 0-100.
             */
            percent: number;
            /**
             * Rate Per Hour
             * @description Packages completed in the trailing hour.
             */
            rate_per_hour: number;
            /**
             * Eta
             * @description Estimated completion timestamp (UTC) from the trailing-hour rate.
             */
            eta?: string | null;
            /**
             * Batches Pending
             * @default 0
             */
            batches_pending: number;
        };
        /** BillDetail */
        BillDetail: {
            /** Bill Id */
            bill_id: string;
            /** Title */
            title: string;
            /** Congress */
            congress?: number | null;
            /** Bill Type */
            bill_type?: string | null;
            /** Number */
            number?: string | null;
            /** Origin Chamber */
            origin_chamber?: string | null;
            /** Origin Chamber Code */
            origin_chamber_code?: string | null;
            /** Introduced Date */
            introduced_date?: string | null;
            /** Update Date */
            update_date?: string | null;
            /** Update Date Including Text */
            update_date_including_text?: string | null;
            /** Latest Action */
            latest_action?: {
                [key: string]: unknown;
            } | null;
            /** Policy Area */
            policy_area?: string | null;
            /** Sponsors */
            sponsors?: {
                [key: string]: unknown;
            }[];
            /** Cosponsors */
            cosponsors?: {
                [key: string]: unknown;
            }[];
            /** Actions */
            actions?: {
                [key: string]: unknown;
            }[];
            /** Summaries */
            summaries?: {
                [key: string]: unknown;
            }[];
            /** Titles */
            titles?: {
                [key: string]: unknown;
            }[];
            /** Text Versions */
            text_versions?: {
                [key: string]: unknown;
            }[];
            /** Committees */
            committees?: {
                [key: string]: unknown;
            }[];
            /** Related Bills */
            related_bills?: {
                [key: string]: unknown;
            }[];
            /** Subjects */
            subjects?: {
                [key: string]: unknown;
            } | null;
            /** Laws */
            laws?: {
                [key: string]: unknown;
            }[];
            /** Constitutional Authority Statement Text */
            constitutional_authority_statement_text?: string | null;
            /** Full Text */
            full_text?: string | null;
            /** Full Text Version Code */
            full_text_version_code?: string | null;
            /** Relationship Counts */
            relationship_counts?: {
                [key: string]: number;
            };
        };
        /** BillDetailResponse */
        BillDetailResponse: {
            bill: components["schemas"]["BillDetail"];
        };
        /** BillSummary */
        BillSummary: {
            /** Bill Id */
            bill_id: string;
            /** Title */
            title: string;
            /** Congress */
            congress?: number | null;
            /** Bill Type */
            bill_type?: string | null;
            /** Number */
            number?: string | null;
            /** Chamber */
            chamber?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** BillTopicsResponse */
        BillTopicsResponse: {
            /** Bill Id */
            bill_id: string;
            /** Topics */
            topics?: components["schemas"]["TopicAssignmentItem"][];
            /** Model Version */
            model_version?: string | null;
        };
        /** BillVotesResponse */
        BillVotesResponse: {
            /** Bill Id */
            bill_id: string;
            /** Votes */
            votes: components["schemas"]["VoteSummary"][];
            /** Total */
            total: number;
        };
        /** BillsResponse */
        BillsResponse: {
            /** Bills */
            bills: components["schemas"]["BillSummary"][];
            /** Total */
            total: number;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Limit
             * @default 50
             */
            limit: number;
        };
        /**
         * BuildState
         * @enum {string}
         */
        BuildState: "idle" | "running" | "succeeded" | "failed";
        /**
         * Chamber
         * @enum {string}
         */
        Chamber: "house" | "senate";
        /** ChamberTimeline */
        ChamberTimeline: {
            /** Chamber */
            chamber: string;
            /** Members */
            members: components["schemas"]["TimelineMember"][];
            /** Groups */
            groups?: components["schemas"]["CongressGroup"][];
        };
        /** CongressGroup */
        CongressGroup: {
            /** Congress */
            congress: number;
            /** Members */
            members: components["schemas"]["TimelineMember"][];
        };
        /** GovInfoCoverage */
        GovInfoCoverage: {
            /** Congress */
            congress: number;
            /**
             * Expected
             * @default 0
             */
            expected: number;
            /**
             * Available
             * @default 0
             */
            available: number;
            /**
             * Pending
             * @default 0
             */
            pending: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Not Available
             * @default 0
             */
            not_available: number;
            /**
             * Complete
             * @default false
             */
            complete: boolean;
            /**
             * Report Found
             * @default false
             */
            report_found: boolean;
        };
        /** GraphBuildStatus */
        GraphBuildStatus: {
            /** @default idle */
            state: components["schemas"]["BuildState"];
            /** Started */
            started?: boolean | null;
            /** Pid */
            pid?: number | null;
            /** Stage */
            stage?: string | null;
            /** Message */
            message?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Versions */
            versions?: {
                [key: string]: string;
            };
        };
        /** GraphLink */
        GraphLink: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Score */
            score: number;
            /** Signal Scores */
            signal_scores?: {
                [key: string]: number;
            };
            /** Shared Topics */
            shared_topics?: string[];
        };
        /** GraphNode */
        GraphNode: {
            member: components["schemas"]["MemberSummary"];
            party_group: components["schemas"]["PartyGroup"];
            /**
             * Is Seed
             * @default false
             */
            is_seed: boolean;
        };
        /** GraphTopicLink */
        GraphTopicLink: {
            /** Member */
            member: string;
            /** Topic Id */
            topic_id: number;
            /** Share */
            share: number;
            /** Bills */
            bills: number;
        };
        /** GraphTopicNode */
        GraphTopicNode: {
            /** Topic Id */
            topic_id: number;
            /** Label */
            label: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndexStatus */
        IndexStatus: {
            /** Name */
            name: string;
            /**
             * Documents
             * @default 0
             */
            documents: number;
        };
        /** IngestProgressJob */
        IngestProgressJob: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Resource */
            resource: string;
            /** Congress */
            congress?: number | null;
            /** From Date */
            from_date?: string | null;
            /** To Date */
            to_date?: string | null;
            /** Fetch Items */
            fetch_items: boolean;
            /** Hydrated */
            hydrated: number;
            /** Discovered */
            discovered: number;
            /** Target */
            target: number;
            /** Remaining */
            remaining: number;
        };
        /** IngestProgressResponse */
        IngestProgressResponse: {
            /** Hydrated */
            hydrated: number;
            /** Discovered */
            discovered: number;
            /** Target */
            target: number;
            /** Remaining */
            remaining: number;
            /** Active Jobs */
            active_jobs: number;
            /**
             * Activity
             * @description Overall ingest activity state.
             */
            activity: string;
            /**
             * Last Progress At
             * @description Most recent durable ingest progress heartbeat.
             */
            last_progress_at?: string | null;
            /** Jobs */
            jobs: components["schemas"]["IngestProgressJob"][];
            backfill?: components["schemas"]["BackfillProgress"] | null;
        };
        /** JobStatusCounts */
        JobStatusCounts: {
            /**
             * Queued
             * @default 0
             */
            queued: number;
            /**
             * Running
             * @default 0
             */
            running: number;
            /**
             * Retrying
             * @default 0
             */
            retrying: number;
            /**
             * Succeeded
             * @default 0
             */
            succeeded: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
        };
        /** MemberActivityItem */
        MemberActivityItem: {
            /** Id */
            id: string;
            /** Document Type */
            document_type: string;
            /** Activity Type */
            activity_type: string;
            /** Title */
            title: string;
            /** Date */
            date?: string | null;
            /** Congress */
            congress?: number | null;
            /** Bill Id */
            bill_id?: string | null;
        };
        /** MemberActivityResponse */
        MemberActivityResponse: {
            /** Items */
            items: components["schemas"]["MemberActivityItem"][];
            /** Total */
            total: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Limit
             * @default 25
             */
            limit: number;
        };
        /** MemberDetail */
        MemberDetail: {
            /** Bioguide Id */
            bioguide_id: string;
            /** Display Name */
            display_name: string;
            /** Party */
            party: string;
            /** State */
            state: string;
            /** Chamber */
            chamber?: string | null;
            /** District */
            district?: number | null;
            /** Term Start Year */
            term_start_year?: number | null;
            /** Term End Year */
            term_end_year?: number | null;
            /** Image Url */
            image_url?: string | null;
            /** Honorific Name */
            honorific_name?: string | null;
            /** Birth Year */
            birth_year?: string | null;
            /** Death Year */
            death_year?: string | null;
            /** Official Website Url */
            official_website_url?: string | null;
            /** Office Address */
            office_address?: string | null;
            /** Phone Number */
            phone_number?: string | null;
            /** Current Member */
            current_member?: boolean | null;
            /** Leadership */
            leadership?: {
                [key: string]: unknown;
            }[];
            /** Party History */
            party_history?: {
                [key: string]: unknown;
            }[];
            /** Terms */
            terms?: components["schemas"]["MemberTerm"][];
            /** Image Attribution */
            image_attribution?: string | null;
        };
        /** MemberProfileResponse */
        MemberProfileResponse: {
            member: components["schemas"]["MemberDetail"];
            /** Recent Activity */
            recent_activity: components["schemas"]["ActivityItem"][];
            /** Topics */
            topics: components["schemas"]["TopicItem"][];
        };
        /** MemberSummary */
        MemberSummary: {
            /** Bioguide Id */
            bioguide_id: string;
            /** Display Name */
            display_name: string;
            /** Party */
            party: string;
            /** State */
            state: string;
            /** Chamber */
            chamber?: string | null;
            /** District */
            district?: number | null;
            /** Term Start Year */
            term_start_year?: number | null;
            /** Term End Year */
            term_end_year?: number | null;
            /** Image Url */
            image_url?: string | null;
        };
        /** MemberTerm */
        MemberTerm: {
            /** Chamber */
            chamber?: string | null;
            /** Congress */
            congress?: number | null;
            /** Start Year */
            start_year?: number | null;
            /** End Year */
            end_year?: number | null;
            /** Member Type */
            member_type?: string | null;
            /** State Code */
            state_code?: string | null;
            /** State Name */
            state_name?: string | null;
            /** District */
            district?: number | null;
        };
        /** MemberTopicTrendPoint */
        MemberTopicTrendPoint: {
            /** Period */
            period: string;
            /** Topic Id */
            topic_id: number;
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /** MemberTopicsResponse */
        MemberTopicsResponse: {
            /** Bioguide Id */
            bioguide_id: string;
            /** Topics */
            topics?: components["schemas"]["TopicItem"][];
            /** Trend */
            trend?: components["schemas"]["MemberTopicTrendPoint"][];
            /** Model Version */
            model_version?: string | null;
            /** Subjects */
            subjects?: components["schemas"]["TopicItem"][];
            /** Policy Areas */
            policy_areas?: components["schemas"]["TopicItem"][];
        };
        /** MembersResponse */
        MembersResponse: {
            /** Members */
            members: components["schemas"]["MemberSummary"][];
            /** Total */
            total: number;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Limit
             * @default 50
             */
            limit: number;
        };
        /** NeighborhoodResponse */
        NeighborhoodResponse: {
            /** Seeds */
            seeds: string[];
            /** Congress */
            congress?: number | null;
            /** Versions */
            versions?: {
                [key: string]: string;
            };
            /** Nodes */
            nodes?: components["schemas"]["GraphNode"][];
            /** Links */
            links?: components["schemas"]["GraphLink"][];
            /** Topic Nodes */
            topic_nodes?: components["schemas"]["GraphTopicNode"][];
            /** Topic Links */
            topic_links?: components["schemas"]["GraphTopicLink"][];
        };
        /**
         * PartyGroup
         * @enum {string}
         */
        PartyGroup: "democratic" | "republican" | "other";
        /** PolicyAreaTrendPoint */
        PolicyAreaTrendPoint: {
            /** Year */
            year: number;
            /** Count */
            count: number;
        };
        /** PolicyAreaTrendSeries */
        PolicyAreaTrendSeries: {
            /** Name */
            name: string;
            /** Total */
            total: number;
            /** Points */
            points: components["schemas"]["PolicyAreaTrendPoint"][];
        };
        /** PolicyAreaTrendsResponse */
        PolicyAreaTrendsResponse: {
            /** Series */
            series?: components["schemas"]["PolicyAreaTrendSeries"][];
            /**
             * Total Bills
             * @default 0
             */
            total_bills: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Types */
            types: string[];
            /** Limit */
            limit: number;
            /** Results */
            results: components["schemas"]["SearchResultItem"][];
        };
        /** SearchResultItem */
        SearchResultItem: {
            /** Id */
            id: string;
            /** Result Type */
            result_type: string;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle?: string | null;
        };
        /**
         * Signal
         * @enum {string}
         */
        Signal: "collaboration" | "voting" | "topic";
        /** SimilarMember */
        SimilarMember: {
            member: components["schemas"]["MemberSummary"];
            /** Score */
            score: number;
            /**
             * Member Sponsored
             * @default 0
             */
            member_sponsored: number;
            /**
             * Neighbor Sponsored
             * @default 0
             */
            neighbor_sponsored: number;
            /**
             * Co Signed
             * @default 0
             */
            co_signed: number;
            /**
             * Shared Votes
             * @default 0
             */
            shared_votes: number;
            /**
             * Agreed Votes
             * @default 0
             */
            agreed_votes: number;
            /**
             * Shared Split Votes
             * @default 0
             */
            shared_split_votes: number;
            /**
             * Agreed Split Votes
             * @default 0
             */
            agreed_split_votes: number;
            /** Shared Topics */
            shared_topics?: string[];
        };
        /** SimilarMembersResponse */
        SimilarMembersResponse: {
            /** Member Id */
            member_id: string;
            signal: components["schemas"]["Signal"];
            /** Congress */
            congress?: number | null;
            /** Graph Version */
            graph_version?: string | null;
            /** Similar */
            similar: components["schemas"]["SimilarMember"][];
        };
        /** StagingStatus */
        StagingStatus: {
            /** Index */
            index: string;
            /**
             * Exists
             * @default false
             */
            exists: boolean;
            /**
             * Documents
             * @default 0
             */
            documents: number;
            /** Production Alias Target */
            production_alias_target?: string | null;
            /**
             * Connected
             * @default false
             */
            connected: boolean;
        };
        /** StateSummary */
        StateSummary: {
            /**
             * Code
             * @description Two-letter state code
             */
            code: string;
            /**
             * Name
             * @description State display name
             */
            name: string;
        };
        /** StateTimelineResponse */
        StateTimelineResponse: {
            /** State Code */
            state_code: string;
            /** State Name */
            state_name: string;
            house: components["schemas"]["ChamberTimeline"];
            senate: components["schemas"]["ChamberTimeline"];
        };
        /** SubjectCount */
        SubjectCount: {
            /** Name */
            name: string;
            /** Count */
            count: number;
        };
        /** SubjectsResponse */
        SubjectsResponse: {
            /** Subjects */
            subjects?: components["schemas"]["SubjectCount"][];
            /** Policy Areas */
            policy_areas?: components["schemas"]["SubjectCount"][];
            /**
             * Total Bills
             * @default 0
             */
            total_bills: number;
        };
        /** SystemStatusResponse */
        SystemStatusResponse: {
            /**
             * Search Connected
             * @default false
             */
            search_connected: boolean;
            /** Indices */
            indices?: components["schemas"]["IndexStatus"][];
            /** Jobs */
            jobs?: {
                [key: string]: components["schemas"]["JobStatusCounts"];
            };
            /** Generated At */
            generated_at?: string | null;
        };
        /** TimelineMember */
        TimelineMember: {
            /** Bioguide Id */
            bioguide_id: string;
            /** Name */
            name: string;
            /** Party */
            party: string;
            /** Congress Start */
            congress_start: number;
            /** Congress End */
            congress_end: number;
        };
        /** TopicAssignmentItem */
        TopicAssignmentItem: {
            /** Topic Id */
            topic_id: number;
            /** Label */
            label: string;
            /** Probability */
            probability: number;
        };
        /** TopicBill */
        TopicBill: {
            /** Bill Id */
            bill_id: string;
            /** Title */
            title?: string | null;
            /** Probability */
            probability: number;
        };
        /** TopicDetailResponse */
        TopicDetailResponse: {
            topic: components["schemas"]["TopicSummary"];
            /** Model Version */
            model_version?: string | null;
            /** Trend */
            trend?: components["schemas"]["TopicTrendPoint"][];
            /** Top Bills */
            top_bills?: components["schemas"]["TopicBill"][];
        };
        /** TopicItem */
        TopicItem: {
            /** Label */
            label: string;
            /** Weight */
            weight: number;
        };
        /** TopicSummary */
        TopicSummary: {
            /** Topic Id */
            topic_id: number;
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Size */
            size: number;
            /** Top Words */
            top_words?: string[];
        };
        /** TopicTrainingStatus */
        TopicTrainingStatus: {
            /**
             * State
             * @default idle
             */
            state: string;
            /** Started */
            started?: boolean | null;
            /** Pid */
            pid?: number | null;
            /** Stage */
            stage?: string | null;
            /** Message */
            message?: string | null;
            /** Model Version */
            model_version?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** TopicTrendPoint */
        TopicTrendPoint: {
            /** Timestamp */
            timestamp: string;
            /** Frequency */
            frequency: number;
            /** Words */
            words?: string | null;
        };
        /** TopicTrendSeries */
        TopicTrendSeries: {
            /** Topic Id */
            topic_id: number;
            /** Label */
            label: string;
            /** Points */
            points: components["schemas"]["TopicTrendPoint"][];
        };
        /** TopicTrendsResponse */
        TopicTrendsResponse: {
            /** Series */
            series: components["schemas"]["TopicTrendSeries"][];
            /** Model Version */
            model_version?: string | null;
        };
        /** TopicsResponse */
        TopicsResponse: {
            /** Topics */
            topics: components["schemas"]["TopicSummary"][];
            /** Model Version */
            model_version?: string | null;
            /** Trained At */
            trained_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VotePartyTotals */
        VotePartyTotals: {
            /**
             * Yea
             * @default 0
             */
            yea: number;
            /**
             * Nay
             * @default 0
             */
            nay: number;
            /**
             * Present
             * @default 0
             */
            present: number;
            /**
             * Not Voting
             * @default 0
             */
            not_voting: number;
        };
        /** VoteSummary */
        VoteSummary: {
            /** Vote Id */
            vote_id: string;
            /** Congress */
            congress?: number | null;
            /** Session Number */
            session_number?: number | null;
            /** Roll Call Number */
            roll_call_number?: number | null;
            /**
             * Chamber
             * @default House
             */
            chamber: string;
            /** Vote Type */
            vote_type?: string | null;
            /** Result */
            result?: string | null;
            /** Question */
            question?: string | null;
            /** Date */
            date?: string | null;
            totals: components["schemas"]["VotePartyTotals"];
            /** Amendment Number */
            amendment_number?: number | null;
            /** Url */
            url?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    topic_training_status_api_v1_admin_topic_training_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicTrainingStatus"];
                };
            };
        };
    };
    topic_training_start_api_v1_admin_topic_training_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicTrainingStatus"];
                };
            };
        };
    };
    member_graph_status_api_v1_admin_member_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphBuildStatus"];
                };
            };
        };
    };
    member_graph_build_api_v1_admin_member_graph_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphBuildStatus"];
                };
            };
        };
    };
    ingest_progress_api_v1_admin_ingest_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestProgressResponse"];
                };
            };
        };
    };
    ingest_snapshot_api_v1_admin_ingest_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminIngestSnapshot"];
                };
            };
        };
    };
    system_status_api_v1_admin_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
    get_states_api_v1_states_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateSummary"][];
                };
            };
        };
    };
    get_timeline_api_v1_states__state_code__timeline_get: {
        parameters: {
            query?: {
                from_congress?: number | null;
                to_congress?: number | null;
            };
            header?: never;
            path: {
                state_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateTimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_districts_api_v1_states__state_code__districts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                state_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_members_api_v1_members_get: {
        parameters: {
            query?: {
                query?: string | null;
                state?: string | null;
                chamber?: string | null;
                party?: string | null;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_member_api_v1_members__bioguide_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bioguide_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_member_activity_api_v1_members__bioguide_id__activity_get: {
        parameters: {
            query?: {
                /** @description Comma-separated document types */
                types?: string | null;
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                bioguide_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    member_topics_api_v1_members__bioguide_id__topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bioguide_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberTopicsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_members_api_v1_members__bioguide_id__similar_get: {
        parameters: {
            query?: {
                signal?: components["schemas"]["Signal"];
                congress?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                bioguide_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarMembersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
                types?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_bills_api_v1_bills_recent_get: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
                query?: string | null;
                congress?: number | null;
                bill_type?: string | null;
                chamber?: string | null;
                subject?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bill_detail_api_v1_bills__bill_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bill_votes_api_v1_bills__bill_id__votes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillVotesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bill_topics_api_v1_bills__bill_id__topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillTopicsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topics_list_api_v1_topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicsResponse"];
                };
            };
        };
    };
    topic_trends_api_v1_topics_trends_get: {
        parameters: {
            query?: {
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicTrendsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topic_detail_api_v1_topics__topic_id__get: {
        parameters: {
            query?: {
                bills?: number;
            };
            header?: never;
            path: {
                topic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subjects_list_api_v1_subjects_get: {
        parameters: {
            query?: {
                congress?: number | null;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    policy_area_trends_api_v1_subjects_policy_area_trends_get: {
        parameters: {
            query?: {
                size?: number;
                start_year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyAreaTrendsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    neighborhood_api_v1_graph_neighborhood_get: {
        parameters: {
            query: {
                member: string[];
                collaboration_weight?: number;
                voting_weight?: number;
                topic_weight?: number;
                congress?: number | null;
                limit?: number;
                party?: components["schemas"]["PartyGroup"][];
                chamber?: components["schemas"]["Chamber"] | null;
                include_topics?: boolean;
                topics_per_member?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeighborhoodResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
