"""Convert a pip requirements.txt into a minimal uv manifest (uv.yaml).

This script produces a simple YAML file listing packages under `packages:`.
It is intentionally conservative; the generated manifest can be edited by hand
to add pins, extras, or Python version metadata expected by `uv`.
"""
import sys
from pathlib import Path


def parse_requirements(path: Path):
    pkgs = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        pkgs.append(line)
    return pkgs


def write_uv_manifest(pkgs, out: Path):
    lines = ["# Generated by scripts/requirements_to_uv.py", "packages:"]
    for p in pkgs:
        lines.append(f"  - {p}")
    out.write_text("\n".join(lines), encoding="utf-8")


def main():
    if len(sys.argv) < 3:
        print("Usage: requirements_to_uv.py <requirements.txt> <uv.yaml>")
        sys.exit(2)
    req = Path(sys.argv[1])
    out = Path(sys.argv[2])
    if not req.exists():
        print(f"Requirements file not found: {req}")
        sys.exit(1)
    pkgs = parse_requirements(req)
    write_uv_manifest(pkgs, out)
    print(f"Wrote {out} with {len(pkgs)} packages")


if __name__ == "__main__":
    main()
